// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxytDzU9nIY3aEy9EH8u5dK_Q-bgB38YI',
    appId: '1:933301578974:web:9c6948f4919179b8e2264f',
    messagingSenderId: '933301578974',
    projectId: 'centrales-conectadas-demo',
    authDomain: 'centrales-conectadas-demo.firebaseapp.com',
    storageBucket: 'centrales-conectadas-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXNarbd81nrUuA5-yCvZw6HSBwnQ5_BDg',
    appId: '1:933301578974:android:7bebcadeae9b149be2264f',
    messagingSenderId: '933301578974',
    projectId: 'centrales-conectadas-demo',
    storageBucket: 'centrales-conectadas-demo.appspot.com',
  );
}
